### ISSUE TITLE
Multiplot followed by replot with hardcopy option.

### ISSUE THREAD

**Issue by zmughal** [drzowie/PDL-Graphics-Gnuplot#40]
I tried the following, but P::G::G (v2.004) gave me an error about setting hardcopy while in multiplot mode:
> Can't set hardcopy while in multiplot mode!

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use PDL;
use PDL::Constants qw(PI);
use PDL::Graphics::Gnuplot;

my $w = gpwin(  );
#$w->option( hardcopy => 'a.png' );  # setting hardcopy before multiplot works

my $theta = zeros(200)->xlinvals(0, 6*PI);

$w->multiplot( layout => [2,1] );
$w->plot( { ls => 1, lw => 2 }, $theta, sin($theta) );
$w->plot( { ls => 2, lw => 2 },  $theta, cos($theta) );
$w->end_multi;

$w->replot( hardcopy => 'a.png' );
$w->close;

<>;
```

It would seem that I shouldn't be in multiplot mode anymore after the call to `end_multi()`, right?

By the way, this is related to how I'm getting P::G::Gnuplot working with IPerl, but there are still issues with my approach <https://github.com/zmughal/p5-Devel-IPerl/issues/29>.

**Comment by drzowie** [comment]
I have to admit, replotting and dealing with multiplots has not been a strong priority, and there are some edge cases that aren’t handled very well.  The issue that’s going on is that the replot() is replaying the status (including multiplot status) of the last plot.  So the object isn’t in multiplot mode when you call replot(), but it switches into multiplot mode as part of the replot operation, since the multiplot flag is part of the stored state.  That’s almost certainly a bug — it would be less wrong to just make the last plot, and the actual desired behavior is to keep track of all the last few plots when in multiplot mode, so that a replot will recreate all of them.

Meanwhile, your best bet for making hard copies of multiplots is to simply ignore the replot mechanism altogether: instead,  change the output device and reissue the various plot calls.

Making replot/hardcopy work with multiplots requires keeping a list of the last few plot commands, which is doable but more involved than a quick fix.  

I’ll gladly implement the solution, but will need a reminder — would you be so kind as to submit this as an Issue in github?  (I’d also take a pull request of course :-)

Cheers,
Craig
