### ISSUE TITLE
Support new terminal options

### ISSUE THREAD

**Issue by d-lamb** [drzowie/PDL-Graphics-Gnuplot#46]
It would be nice if there was an automatic way of supporting new terminal options.  I'm not sure if there are any native gnuplot commands for this--I didn't see anything right away.  For example, with Gnuplot 5.0 many terminals support a "background" option, but including that in P::G::G might break support for 4.x Gnuplots.

**Comment by drzowie** [comment]
I'll keep this open for now.  Gnuplot itself doesn't have any good self-discovery beyond the version number mechanism, so it would be hard to adapt.  

There are similar issues in 5.0 with curve options changing -- e.g. "dashtype" is now a curve option, rather than the older "dashed / no dashed" terminal option.  (I just pushed up support for the new curve option)

**Comment by drzowie** [comment]
OK, I've updated all terminals that now support "background" and didn't before.  I'm closing this.  If the user is using an old gnuplot (e.g. 4.2) and gets an error, so be it.  Soon I'll deprecate 4.x gnuplots, which should make that less of an issue.
