### ISSUE TITLE
barfing after sending cleanup command

### ISSUE THREAD

**Issue by bruceravel** [drzowie/PDL-Graphics-Gnuplot#48]
Hi!
PDL::Graphics::Gnuplot is great, but I am not a big fan of [this (and similar) lines](https://github.com/drzowie/PDL-Graphics-Gnuplot/blob/master/lib/PDL/Graphics/Gnuplot.pm#L3166).

The [current manner (here and elsewhere)](https://github.com/drzowie/PDL-Graphics-Gnuplot/blob/master/lib/PDL/Graphics/Gnuplot.pm#L3151-L3156) of filtering out non-malignant chatter from gnuplot works as far as it goes, but lets through other unproblematic chatter.  The places where such chatter is sent to `PDL::barf` are less problematic because I can overload `PDL::barf` and do my own filtering.  The problem with printing directly to STDERR is that the only way to do my own filtering would be to hijack STDERR, which is not my favorite technique.

So my request is that you `use Carp` in PDL::Graphics::Gnuplot and that you `carp` gnuplot's chatter rather than print to STDERR at the line I cited above and elsewhere.  That behavior seems closer in spirit to `PDL::barf`.

Cheers,
B

**Comment by drzowie** [comment]
Thanks, Bruce!

That is a really astute observation and I should totally be using Carp instead of vomiting all over STDERR like a hayseed in a pumpkin field.

I would be *very* glad to honor a pull request if you felt like making the patches and pushing them up somewhere; or else I can get to it myself RSN.  For the latter, I request kindly that you file an Issue on github, I’m pretty swamped just now and I don’t want this to fall into the noise.

I’d also welcome suggestions or pull requests for better filtering of the gnuplot output — it’s a non-trivial problem.

Best,
Craig

**Comment by bruceravel** [comment]
> That is a really astute observation and I should totally be using Carp instead of vomiting all over
> STDERR like a hayseed in a pumpkin field.

OK, that made me laugh out loud at the gym.  

I'll prep a pull request tomorrow.
