### ISSUE TITLE
looong ascii plot fails on cygwin64/win7

### ISSUE THREAD

**Issue by devel-chm** [drzowie/PDL-Graphics-Gnuplot#56]
The test works for number of elements up through 4000 at least and fails for 5000 and up.  My guess is that some buffer limit is being reached causing the process to fail.  Any ideas on how to diagnose further?

**Comment by drzowie** [comment]
Hmmm.   Sorry it took so long to get back to you.  Have a look at Issue 57, which seems to be related.  The $ms_io_braindamage flag is in place because Microsoft Windows pipelike I/O works very differently from POSIX I/O, and I'm not sure how to fix it.  You might like to look and see if you're hanging or buzzing in the echo-eater loop.

**Comment by drzowie** [comment]
This seems to be related to 57 & 61, which were just resolved, so I'm going to close this now.
